### ISSUE TITLE
Unifi instructions

### ISSUE THREAD

**Issue by ghost** [mbierman/unifi-installer-for-Firewalla#2]
Hey- this isn't so much an issue as a question! Once I am able to ssh into my Firewalla, would I just copy 

curl -s -L -C- https://raw.githubusercontent.com/mbierman/unifi-installer-for-Firewalla/main/unifi_docker_install.sh | cat <(cat <(bash))

into the terminal and I'm good to go? 

That seems way simpler than the Firewalla instructions or this:

https://github.com/jacobalberty/unifi-docker

Thanks!

**Comment by ghost** [comment]
Hey-

So I figured it out and have had fun learning a bit!  My one question if you can help me is.....The docker in Terminal told me to open the https://172..... in my browser to set up the Unifi controller. However, nothing happens when I paste that into my browser. I already had my Unifi controller set up online before. It appears my docker is working since the apps work when I'm not logged into the browser.

**Comment by mbierman** [comment]
That's correct. The second link is the docker image this script used too. This script is just a custom installer for firewalla.

**Comment by mbierman** [comment]
You might need to stop and restart the docker container. I'm not sure why, but that happens sometimes after install.

**Comment by ghost** [comment]
Hey- so I was wrong about the controller working... I had the controller open in a different browser.

So...basically I have no idea what I'm doing and maybe should stop. When I ssh into the Firewalla and run: 
cd /data
curl https://raw.githubusercontent.com/mbierman/unifi-installer-for-Firewalla/main/unifi-uninstall.sh > /data/unifi-uninstall.sh

I get 'permission denied'. Is there a way to tell if it is actually installed or has been uninstalled? If I do "sudo docker ps" nothing shows up.

When I quit terminal and ssh again, I will copy and paste your instal link. Then the installer seems to run and run and run....check out my screenshot

<img width="566" alt="Screenshot 2023-02-26 at 2 16 42 PM" src="https://user-images.githubusercontent.com/96595807/221438049-7c1f2f54-8b4c-4eac-9d3e-38f381b11c64.png">


Can I pay you to make a YouTube tutorial? It seems like this should be easier than I am making it! I shouldn't have messed with it when. Is it likely a rule blocking "https://172.16.1.2:8443." Last time I thought I had the docker installed, that wouldn't load when I pasted it into my browser

Thanks again!

**Comment by mbierman** [comment]
Try the version I just posted. It should make sure the permissions are correct and get rid of those errors for you. Always happy to accept donations to my coffee fund if you are so inclined. ;)

**Comment by bryanjw** [comment]
@bfraase I had the same issue after installation. I checked the Firewalla guide and noticed under step 2 it said "This command may need to be run every time the docker container is started." So I ran those2 commands again and the Controller came right up. Try this:

sudo ip route add 172.16.1.0/24 dev br-$(sudo docker network ls | awk '$2 == "unifi_default" {print $1}') table lan_routable
sudo ip route add 172.16.1.0/24 dev br-$(sudo docker network ls | awk '$2 == "unifi_default" {print $1}') table wan_routable

@mbierman Is this the case for your instance as well? I even restarted the docker container to test and lost it again. Running those two routing rules again brought it back. Any ideas to not have to do this? I haven't tested it yet but I'm inclined to see what happens if the Firewalla loses power.

Firewalla guide:
https://help.firewalla.com/hc/en-us/articles/360053441074#h_01FM2T5Q0VDW0CRW7ZNPXB52T1

**Comment by mbierman** [comment]
@bfraase I have to add a few other things anyway so I will add this use case into the script to make it more reliable.

**Comment by ghost** [comment]
@mbierman I might just give up... I have no idea what I'm doing...this still happens to me....I really appreciate all of your help with all of this!

<img width="584" alt="Screenshot 2023-02-27 at 8 39 46 PM" src="https://user-images.githubusercontent.com/96595807/223904945-f2894a77-930d-40ba-a250-3a8ff7f4a0fd.png">

This is what I do....
1. ssh into my firewall
2. paste in your install code
3. watch it start docker for up to an hour......but only get the dots and nothing happened

Am I missing a step?

**Comment by mbierman** [comment]
Sorry for the delay. Try the new version. I fixed a bug that sometimes bit people. Use the uninstaller first and then install. Super easy now.
